name: artifacts
on: [push]
env:
  ARTIFACT_NAME: artifact_thing
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .

